### ISSUE TITLE
Support for automatic hyperparameter optimization

### ISSUE THREAD

**Issue by datawranglerai** [mlampros/fastText#1]
Would be great to see something similar to the Python module's implementation of supervised training.

````
list_params <- list(
    command = "supervised",
    input = 'cooking.train',
    autotuneValidationFile = 'cooking.valid', 
    autotuneMetric = "f1:__label__baking",
    autotuneDuration = 600,
    autotuneModelSize = "2M"
)

**Comment by mlampros** [comment]
hi @datawranglerai,

it seems that the ```-autotune-validation``` is a [new feature](https://fasttext.cc/docs/en/autotune.html), there are also [open issues](https://github.com/facebookresearch/fastText/issues/913) as it's currently under active development. I implemented this version of the fastText package on March 2019 and I'm currently only concentrated on fixing bugs (if any). If you are in a hurry I would suggest to take a look to another R version of the fasttext where it's [mentioned by the author](https://github.com/pommedeterresautee/fastrtext/issues/38) that he considers implementing this ```-autotune-validation``` feature in the next few days.

**Comment by datawranglerai** [comment]
> hi @datawranglerai,
> 
> it seems that the `-autotune-validation` is a [new feature](https://fasttext.cc/docs/en/autotune.html), there are also [open issues](https://github.com/facebookresearch/fastText/issues/913) as it's currently under active development. I implemented this version of the fastText package on March 2019 and I'm currently only concentrated on fixing bugs (if any). If you are in a hurry I would suggest to take a look to another R version of the fasttext where it's [mentioned by the author](https://github.com/pommedeterresautee/fastrtext/issues/38) that he considers implementing this `-autotune-validation` feature in the next few days.

Thanks for the explanation - makes sense. Just also want to say that I really appreciate the work you've put into the package so far, I've really enjoyed using it.
